### ISSUE TITLE
Broken automation on Java 12

### ISSUE THREAD

**Issue by vbmacher** [emustudio/emuStudio#152]
**emuStudio (0.38b) + Java(TM) SE Runtime Environment (build 1.8.0_241-b07)**

Automation runs OK, input is in file `terminalADM-3A.in` and output in `terminalADM-3A.out`.

```
"C:\Program Files (x86)\Java\jre1.8.0_241\bin\java" -jar emuStudio.jar --config "MITS Altair8800" --input z127.asm --output output.html --auto --nogui
```
**emuStudio (0.38b) + Java(TM) SE Runtime Environment (build 12.0.2+10)**

Automation is broken:

```
Loading virtual computer: MITS Altair8800
Input file name: z127.asm
Output file name: output.html
Turning automatization on.
Loading virtual computer: MITS Altair8800
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
```

**emuStudio (0.40-SNAPSHOT) + Java(TM) SE Runtime Environment (build 12.0.2+10)**

Automation will run, but is stuck at `[INFO] Running emulation...`

**emuStudio (0.40-SNAPSHOT) + Java(TM) SE Runtime Environment (build 1.8.0_241-b07)**

The same - runs, and then stuck.

**Comment by vbmacher** [comment]
Fixed on Java 11
