### ISSUE TITLE
Usability questions

### ISSUE THREAD

**Issue by mjsir911** [emustudio/emuStudio#164]
Hello,

I am trying to use emuStudio to see if it is what I am looking for and I'm running into some problems early on into the process. Was wondering if some pointers could be provided as to what I'm doing wrong.

```bash
$ curl -O https://github.com/emustudio/emuStudio/releases/download/RELEASE-0.39/emuStudio-0.39.zip
$  unzip emuStudio-0.39.zip -d emuStudio-0.39
$  cd emuStudio-0.39
$ java -jar emuStudio.jar
# this works and opens the GUI
$ java -jar compilers/as-8080.jar 
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: emulib/plugins/compiler/Compiler$CompilerListener
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: emulib.plugins.compiler.Compiler$CompilerListener
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	... 7 more
$ java -jar devices/88-disk.jar  --help
MITS 88-DISK emuStudio plug-in, version 0.39
# this one does work
```

I'm getting the crash when trying to run the assembler from the command line as outlined [here](https://www.emustudio.net/docuser/mits_altair_8800/index/#installation-and-run), any ideas?

**Comment by mjsir911** [comment]
Update: this is not ideal but it runs if I move `as-8080.jar` into the top directory outside of `compilers`

**Comment by vbmacher** [comment]
Hello, thanks for posting the question!

In version 0.39 the compilers are runnable, however they have hardcoded paths to libraries (in manifest file inside the jar), pointing to in `lib/` subdirectory. Soon there will be released 0.40 (in this summer) which will be bundled with startup scripts for each runnable plugin.

**Comment by vbmacher** [comment]
And yes, the documentation is not accurate in this. Thanks

**Comment by vbmacher** [comment]
@mjsir911 Hi, new emuStudio has been released few days ago. The usability should have been improved now.

For example, if you have emuStudio unzipped (and installed at least Java 11 either on your `PATH` or in `JAVA_HOME` variable), you can run the compiler as-8080 as follows (in Linux):

```
bin/as-8080 
```

and in Windows as:

```
bin\as-8080.bat
```


For more info check the documentation, e.g.: https://www.emustudio.net/documentation/user/altair8800/as-8080
