### ISSUE TITLE
SSEM emulation is incredibly slow on Windows

### ISSUE THREAD

**Issue by vbmacher** [emustudio/emuStudio#181]
Tested with Java 14

**Comment by vbmacher** [comment]
```
[ERROR] Memory listener error
java.lang.ArrayIndexOutOfBoundsException: Index 128 out of bounds for length 128
        at net.emustudio.plugins.memory.ssem.MemoryContextImpl.readWord(MemoryContextImpl.java:46)
        at net.emustudio.plugins.memory.ssem.MemoryContextImpl.readWord(MemoryContextImpl.java:26)
        at net.emustudio.plugins.device.ssem.display.DisplayGui$1.memoryChanged(DisplayGui.java:53)
        at net.emustudio.emulib.plugins.memory.AbstractMemoryContext.lambda$notifyMemoryChanged$0(AbstractMemoryContext.java:89)
        at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:804)
        at java.base/java.util.concurrent.CopyOnWriteArraySet.forEach(CopyOnWriteArraySet.java:425)
        at net.emustudio.emulib.plugins.memory.AbstractMemoryContext.notifyMemoryChanged(AbstractMemoryContext.java:87)
        at net.emustudio.plugins.memory.ssem.MemoryContextImpl.writeWord(MemoryContextImpl.java:60)
        at net.emustudio.plugins.memory.ssem.MemoryContextImpl.writeWord(MemoryContextImpl.java:26)
        at net.emustudio.plugins.cpu.ssem.EmulatorEngine.writeInt(EmulatorEngine.java:112)
        at net.emustudio.plugins.cpu.ssem.EmulatorEngine.step(EmulatorEngine.java:82)
        at net.emustudio.plugins.cpu.ssem.EmulatorEngine.run(EmulatorEngine.java:127)
        at net.emustudio.plugins.cpu.ssem.CpuImpl.call(CpuImpl.java:147)
        at net.emustudio.plugins.cpu.ssem.CpuImpl.call(CpuImpl.java:44)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:832)
```

**Comment by vbmacher** [comment]
Slowness was caused by imprecise `LockSupport.parkNanos()` on Windows. The exception was caused by wrong handling of memory addresses. The commit above also improved measuring how many nanos we should wait after each instructions to get 700 instructions/second.
