### ISSUE TITLE
88-disk: when attaching more devices, sometimes a ConcurrentModificationException is raised

### ISSUE THREAD

**Issue by vbmacher** [emustudio/emuStudio#183]
```
[INFO] [device=LSI ADM-3A Terminal] Device was attached to 88-SIO
Exception in thread "Thread-13" java.util.ConcurrentModificationException
        at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1584)
        at java.base/java.util.HashMap$EntryIterator.next(HashMap.java:1617)
        at java.base/java.util.HashMap$EntryIterator.next(HashMap.java:1615)
        at com.electronwill.nightconfig.core.utils.TransformingIterator.next(TransformingIterator.java:34)
        at com.electronwill.nightconfig.toml.TableWriter.writeNormal(TableWriter.java:53)
        at com.electronwill.nightconfig.toml.TableWriter.writeNormal(TableWriter.java:43)
        at com.electronwill.nightconfig.toml.TableWriter.writeNormal(TableWriter.java:88)
        at com.electronwill.nightconfig.toml.TableWriter.writeNormal(TableWriter.java:43)
        at com.electronwill.nightconfig.toml.TableWriter.writeNormal(TableWriter.java:103)
        at com.electronwill.nightconfig.toml.TableWriter.writeNormal(TableWriter.java:43)
        at com.electronwill.nightconfig.toml.TomlWriter.write(TomlWriter.java:30)
        at com.electronwill.nightconfig.core.file.WriteAsyncFileConfig.save(WriteAsyncFileConfig.java:114)
        at com.electronwill.nightconfig.core.file.WriteAsyncFileConfig.access$300(WriteAsyncFileConfig.java:23)
        at com.electronwill.nightconfig.core.file.WriteAsyncFileConfig$WriteCompletedHandler.completed(WriteAsyncFileConfig.java:147)
        at com.electronwill.nightconfig.core.file.WriteAsyncFileConfig$WriteCompletedHandler.completed(WriteAsyncFileConfig.java:142)
        at java.base/sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:127)
        at java.base/sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:282)
        at java.base/sun.nio.ch.WindowsAsynchronousFileChannelImpl$WriteTask.completed(WindowsAsynchronousFileChannelImpl.java:653)
        at java.base/sun.nio.ch.Iocp$EventHandlerTask.run(Iocp.java:387)
        at java.base/sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:112)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:832)
```

**Comment by vbmacher** [comment]
This is already fixed by rewriting of 88-dcdd gui
