### ISSUE TITLE
Regression tests for 0.41

### ISSUE THREAD

**Issue by vbmacher** [emustudio/emuStudio#315]
Test whole emuStudio before release.

- z80-cpu, 8080-cpu: Frequency in settings
- Z80-cpu: default frequency 4 KHz
- z80-cpu, 8080-cpu: frequency spinner in status now reads real frequency

**Comment by vbmacher** [comment]
- RASP, RAM, SSEM: implement Load image, dump memory and clear memory
- RASP memory: read `.brasp` files

**Comment by vbmacher** [comment]
- emuStudio application: reuse lexer on syntax highlighting
- emuStudio application: use better monospaced font (Fira Code)
- RASP-cpu: redesign status panel, add address debug column
- 88-sio: disable interrupts by default (due to CP/M 2.2)
- document better compiler examples

**Comment by vbmacher** [comment]
- Fix RAM/RASP serialization/deserialization

**Comment by vbmacher** [comment]
TODO: Support negative constants in RAM/RASP

**Comment by vbmacher** [comment]
- SSEM memory: GUI refactoring + fixes
- byte-mem: refactoring

**Comment by vbmacher** [comment]
TODO: SSEM-memory: cannot open binary file

**Comment by vbmacher** [comment]
- Brainduck: load source, emulate, stop, load source, compile, reset, emulate and:

```
[ERROR] Unexpected error during emulation
java.util.concurrent.ExecutionException: java.util.NoSuchElementException
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at net.emustudio.emulib.plugins.cpu.AbstractCPU$CPUWatchTask.run(AbstractCPU.java:98)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.util.NoSuchElementException: null
	at java.base/java.util.ArrayDeque.removeFirst(ArrayDeque.java:363)
	at java.base/java.util.ArrayDeque.pop(ArrayDeque.java:594)
	at net.emustudio.plugins.cpu.brainduck.EmulatorEngine.step(EmulatorEngine.java:135)
	at net.emustudio.plugins.cpu.brainduck.CpuImpl.stepInternal(CpuImpl.java:156)
	at net.emustudio.plugins.cpu.brainduck.CpuImpl.call(CpuImpl.java:128)
	at net.emustudio.plugins.cpu.brainduck.CpuImpl.call(CpuImpl.java:43)
	... 4 common frames omitted
```

**Comment by vbmacher** [comment]
TODO: byte-mem: ASCII mode stopped working

**Comment by vbmacher** [comment]
TODO:

- Altair DOS doesnt work
- byte-mem: find sequence GUI (find button is too small)
- byte-mem: ASCII mode stopped working
